### ISSUE TITLE
Candidate Registration failure

### ISSUE THREAD

**Issue by seunoyebode** [LaravelDaily/Laravel-Job-Board-Demo#1]
Hi, Thanks for this amazing app.

This error pops up when trying to register as a candidate.

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`job-board-demo`.`role_user`, CONSTRAINT `role_user_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)) (SQL: insert into `role_user` (`role_id`, `user_id`) values (3, 5))`

**Comment by PovilasKorop** [comment]
@seunoyebode fixed it, the seeds were wrong, sorry. You need to re-seed database with `php artisan migrate:fresh --seed`
